### ISSUE TITLE
xgboost hangs indefinitely

### ISSUE THREAD

**Issue by SultanOrazbayev** [coiled/coiled-runtime#146]
I am trying to use xgboost with coiled, but it hangs indefinitely.

For a reproducible example, I tried running @rrpelgrim code in https://coiled.io/blog/dask-xgboost-python-example/.

Steps to reproduce:

1. create `environment.yml`:

```yaml
name: coiled_xgboost
channels:
- conda-forge
dependencies:
- python=3.9
- coiled-runtime=0.0.3
- xgboost=1.5.1
- dask-ml=2022.1.22
```

2. use `coiled` to create this environment for workers:

```python
from coiled import create_software_environment

create_software_environment(
    name="my-conda-env",
    conda="environment.yml",
)
```

3.  Execute the following code (it will hang on the `dispatched_train` task):

```python
from coiled import Cluster
cluster = Cluster(software="my-conda-env", n_workers=1)

from distributed import Client
client = Client(cluster)

import dask.dataframe as dd

# download data from S3
data = dd.read_parquet(
    "s3://coiled-datasets/synthetic-data/synth-reg-104GB.parquet/", 
    compression="lz4",
    storage_options={"anon": True, 'use_ssl': True},
)

# select the first 10 partitions
data_local = data.partitions[0:10]
data_local = data_local.persist()


from dask_ml.model_selection import train_test_split
# Create the train-test split
X, y = data_local.iloc[:, :-1], data_local["target"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, shuffle=True, random_state=21
)

import xgboost as xgb
# Create the XGBoost DMatrix for our training and testing splits
dtrain = xgb.dask.DaskDMatrix(client, X_train, y_train)
dtest = xgb.dask.DaskDMatrix(client, X_test, y_test)

# Set model parameters (XGBoost defaults)
params = {
    "max_depth": 6,
    "gamma": 0,
    "eta": 0.3,
    "min_child_weight": 30,
    "objective": "reg:squarederror",
    "grow_policy": "depthwise"
}

# THIS STEP WILL HANG
# train the model
output = xgb.dask.train(
    client, params, dtrain, num_boost_round=5,
    evals=[(dtrain, 'train')]
)
```

4. (OPTIONAL), the local version of the above works fine:

```python
from dask.distributed import Client, LocalCluster

# local dask cluster
cluster = LocalCluster(n_workers=4)
client = Client(cluster)

import dask.dataframe as dd

# download data from S3
data = dd.read_parquet(
    "s3://coiled-datasets/synthetic-data/synth-reg-104GB.parquet/", 
    compression="lz4",
    storage_options={"anon": True, 'use_ssl': True},
)

# select the first 10 partitions
data_local = data.partitions[0:10]
data_local = data_local.persist()

from dask_ml.model_selection import train_test_split
# Create the train-test split
X, y = data_local.iloc[:, :-1], data_local["target"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, shuffle=True, random_state=21
)

import xgboost as xgb
# Create the XGBoost DMatrix for our training and testing splits
dtrain = xgb.dask.DaskDMatrix(client, X_train, y_train)
dtest = xgb.dask.DaskDMatrix(client, X_test, y_test)

# Set model parameters (XGBoost defaults)
params = {
    "max_depth": 6,
    "gamma": 0,
    "eta": 0.3,
    "min_child_weight": 30,
    "objective": "reg:squarederror",
    "grow_policy": "depthwise"
}

# train the model
output = xgb.dask.train(
    client, params, dtrain, num_boost_round=5,
    evals=[(dtrain, 'train')]
)
```

**Comment by ntabris** [comment]
Yes, there was a problem with xgboost on Coiled with v2 cluster. This has been addressed for `coiled=0.2.3` and `xgboost>=1.6`, those should work currently.

**Comment by ncclementi** [comment]
@SultanOrazbayev Thanks you for mentioning this, as Nat explained we have been working on a fix and eventually we will add xgboost to the coiled-runtime see https://github.com/coiled/coiled-runtime/pull/131

For now, if you install xgboost, you'll need to use pip to get `xgboost >=1.6` as it's not available in conda-forge due to an upstream conda-forge bug that needs to be resolved see https://github.com/conda-forge/xgboost-feedstock/pull/88#issuecomment-1126284621 .

**Comment by SultanOrazbayev** [comment]
FWIF, I tried it just now with the following environment, btu the issue remains:

```python
name: coiled_xgboost
channels:
- conda-forge
dependencies:
- python=3.9
- coiled-runtime=0.0.3
- dask-ml=2022.1.22
- pip=22.1.1
- pip:
    - xgboost==1.6.1
```

In case it might be useful, my session logs are here: https://cloud.coiled.io/sultanorazbayev/clusters/30208/details

**Comment by ncclementi** [comment]
@SultanOrazbayev Just for checking purposes what version of coiled was installed?

**Comment by SultanOrazbayev** [comment]
Great, it works now! Here's the environment I used:

```yaml
name: coiled_xgboost
channels:
- conda-forge
dependencies:
- python=3.9
- coiled-runtime=0.0.3
- coiled=0.2.3
- dask-ml=2022.1.22
- pip=22.1.1
- pip:
    - xgboost==1.6.1
```

**Comment by ntabris** [comment]
I’ve been thinking about this more and probably should just switch to
network mode that doesn’t require specific versions/settings to make
xgboost work. I’ll try some things but potentially we’d get that out early
next week.
